const Erros = {
  CPF_INVALIDO: "CPF_INVALIDO",
  ID_INVALIDO: "ID_INVALIDO",
  SENHA_INVALIDA: "SENHA_INVALIDA",
  NOME_INVALIDO: "NOME_INVALIDO",
  NOME_GRANDE: "NOME_GRANDE",
  NOME_PEQUENO: "NOME_PEQUENO",
  NOME_SEM_SOBRENOME: "NOME_SEM_SOBRENOME",
  NOME_VAZIO: "NOME_VAZIO",
  TAG_INVALIDA: "TAG_INVALIDA",
} as const;
export default Erros;
